### ISSUE TITLE
Add Clinch-SDL2 for some reason...

### ISSUE THREAD

**Issue by BradWBeer** [BradWBeer/clinch#41]
I don't know why this is important to me.

**Comment by rvedam** [comment]
SDL is moving forward with SDL 2.0 and it might be useful moving forward to keep up to date with that project so that people looking for code examples they would like to port over to CL using clinch-sdl can do so. I was thinking (I'm not entirely sure this is already done) to write a higher-level interface that acts as a factory between glfw and sdl and sdl2, constructing the appropriate window object based on a keyword parameter passed into the factory. Just a thought

**Comment by BradWBeer** [comment]
Sorry I missed your comment. I've been offline for a while. I agree. I would like to do something like that eventually. It's a much better approach than trying to make all the libraries behave the same.

**Comment by BradWBeer** [comment]
Completely moving Clinch to SDL2. There is no longer any clinch-glfw, clinch-sdl or clinch-sdl2. A [new issue](#54), has been created.
